### ISSUE TITLE
SSL error on install

### ISSUE THREAD

**Issue by mmeinerz** [OpenC3/docs.openc3.com#67]
I am getting an SSL verification error on the initial install.  I have created and installed a certificate as described in the installation instructions but am still getting errors through the install script.  Any thoughts out there?

![Screenshot 2023-09-27 at 6 18 55 PM](https://github.com/OpenC3/docs.openc3.com/assets/146776969/3f2e7901-6133-481b-b4ce-646859901b2b)

**Comment by ryanmelt** [comment]
You will probably need to have a proper John Hopkins certificate authority file pointed to by SSL_CERT_FILE environment variable.

COSMOS 4 is End Of Life and we generally recommend everyone upgrade to COSMOS 5.
